#!/usr/bin/env python3
"""Generate pyscript.toml files section for local dev / GH Pages."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "pyscript.toml"
INDEX = ROOT / "index.html"

INCLUDE_DIRS = ("wod_chargen", "app")
EXTENSIONS = {".py", ".json"}


def collect_pyscript_paths(root: Path | None = None) -> set[str]:
    """Return repo-relative paths that must appear in pyscript.toml."""
    base = root or ROOT
    paths: set[str] = set()
    for dirname in INCLUDE_DIRS:
        for path in sorted((base / dirname).rglob("*")):
            if path.suffix not in EXTENSIONS or path.name.startswith("."):
                continue
            paths.add(path.relative_to(base).as_posix())
    return paths


def compute_cache_version(root: Path, paths: set[str]) -> str:
    digest = hashlib.sha256()
    for rel in sorted(paths):
        digest.update(rel.encode("utf-8"))
        digest.update((root / rel).read_bytes())
    return digest.hexdigest()[:12]


def render_pyscript_toml(paths: set[str], cache_version: str) -> str:
    lines = [
        "# Auto-generated by scripts/generate_pyscript_config.py — do not edit by hand\n",
        f"# cache_version={cache_version}\n",
        "[files]\n",
    ]
    for rel in sorted(paths):
        lines.append(f'"{rel}" = "{rel}"\n')
    return "".join(lines)


def parse_pyscript_toml(path: Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    paths: set[str] = set()
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith('"') or " = " not in line:
            continue
        key, _value = line.split(" = ", 1)
        paths.add(key.strip('"'))
    return paths


def parse_cache_version(path: Path) -> str | None:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# cache_version="):
            return line.split("=", 1)[1].strip()
    return None


def update_index_cache_version(version: str) -> None:
    html = INDEX.read_text(encoding="utf-8")
    html = re.sub(r'app/main\.py\?v=[^"]+', f'app/main.py?v={version}', html)
    html = re.sub(r'pyscript\.toml\?v=[^"]+', f'pyscript.toml?v={version}', html)
    INDEX.write_text(html, encoding="utf-8")


def main() -> None:
    paths = collect_pyscript_paths()
    cache_version = compute_cache_version(ROOT, paths)
    OUT.write_text(render_pyscript_toml(paths, cache_version), encoding="utf-8")
    update_index_cache_version(cache_version)
    print(f"Wrote {len(paths)} file mappings to {OUT} (cache_version={cache_version})")


if __name__ == "__main__":
    main()
